### ISSUE TITLE
Stop

### ISSUE THREAD

**Issue by parkerat2** [ejcole/ChopStyx#1]
Collaborate and Listen

**Comment by matts-dev** [comment]
Thinking of ways to visualize a state for debugging, how about this:
We sort each hand from lowest to highest. We display you (agent) first, then opponent. We separate them with | symbol.
<your hands> | <opponent hands>

e.g.
3 4 | 1 2

**Comment by parkerat2** [comment]
Needs a marker for whose turn it is.  Maybe an *

**Comment by matts-dev** [comment]
Sure.
