### ISSUE TITLE
Getting Started.

### ISSUE THREAD

**Issue by matts-dev** [ejcole/ChopStyx#2]
I've created two folders. Python and Java. I set up an pycharm project for us to share; it is the Python folder. There is a readme for how to open the project. 

You guys are free to make additional folders (besides java/python) and work on those if you like. 

I figure the Python folder will be our main (ie shared) project. I'd like for us to make branches and do pull requests for when modifying that code if you guys are okay with that. (Why not get a little more practice with SE practices?)

But if you make your own folder for some "spikes" as Dr. Fenwick calls them, then you don't need to worry about pull requests since it will be your own code. But let's be proper as much as possible about our shared code. 

Let me know what you guys think about that, nothing is set in stone yet. :) We can still change the folder structure if we want or how we're doing things. :)

p.s. I think we're missing one group mate on our repo.

edit: I've created a project for us to monitor progress, but that might be overkill for this project.

**Comment by ejcole** [comment]
Looks good, I think we have everyone on it now.
