### ISSUE TITLE
CSVs

### ISSUE THREAD

**Issue by matts-dev** [ejcole/ChopStyx#4]
I've created two CSVs from our java prototype. I will clean up the code some more tomorrow, but it should be fairly readable. I'd still like to get a python implementation going and submit that instead. But as a fallback we have some CSVs to use; I'm not convinced they are optimal though because they only marginally beat a randomized AI. I haven't tested the CSVs against myself either.  Here's some notes on the implementation. 

I implemented what we talked about in class in java with a few modifications.

We still create all states upfront.

We still run minimax on all states.

However I've modified minimax slightly.

Minimax no longer returns a utility value. It returns a depth to solution. Paths to solutions for the min player give negative depths. Paths to solutions for the max player give positive depths. Encountered loops give 0 depths. Comparison between actions still uses a utility function; it just uses the the returned depth value in the utility function to calculate it on the fly. Why use depths instead of utility values? By returning depths we can cache the depth a state takes to win for later encounters; we however should not cache the utility value of a state because it depends  on the depth; because we need to adjust the utility function depending on how we get to the state. Thus, if we cache the depth a state takes to win in a hashmap, we can calculate its utility function on the fly considering a different paths depth. We must have two different sets for the min player and the max player. This should give a massive speed up on the 3 hand game. 

Minimax now has an explored set that tracks states previously visited. The explored set is not used for loop detection. It however is used to cache depths to solutions for when this node is encountered. 

The algorithm does loop detection with another hashset called the pathSet. The pathset has elements frequently added to and removed from. Anytime a minimax branch encounters a node in the path set, it returns a 0. A 0 depth indicates a loop. When we first visit a state, we add it to the explored set and temporarily to the pathset; then we run minimax on all its children and remove the node from the path set when all children have been calculated. each child is added to the path set recursively and added to the explored set. When a child reaches an explored node grandchild, it simply uses the cached depth from when we first explored the grandchild node. It seems that the path may reach a node that hasn't had its depth cached yet; this isn't the case because a node that hasn't had its depth cached yet will be in the pathSet, and encountering that node is a loop and it will return 0.

Some side notes:

UTILITY VALUE: if the max player is faced with children that all lead to the min player winning, it chooses the maximum of the utility function. Since this is -e^(-d), this will correspond to the largest path for the min player. This is because e^-d shrinks. Long paths will approach 0. For example, a short path may give us '2', and a long path gives us '0.005'. When we negative these values (for the min player) we get -2 and -0.005; when the max player chooses the max of these two values, it will choose -0.005; which corresponds to the largest path for the min player giving it more opportunities to make mistakes.

UTILITY VALUE AND ZERO
The max player will always choose 0 to any of the min player paths (because they will be negative). This means the max player will prefer loops to losses. The same can be said for the min player, it will prefer 0 to any positive paths.

**Comment by ejcole** [comment]
Interesting, ill look at this more and see what i can do in python.  Generating the CSVs for 3 hands should be simple when we get 2 hands working right.

**Comment by mattstone22133** [comment]
Hey guys, my number is 336 432 0265. If you guys wanna meet up for lunch to talk about the project (or slightly after) I can do that. I have to leave town today but I can work on it from my laptop. I'm drafting up a python version of the augmented minimax algorithm

**Comment by matts-dev** [comment]
If you guys want to meet up, shoot me an email and I'll send you my mobile. stonemj1@appstate.edu

**Comment by ejcole** [comment]
I'm eating now I can come in around 1ish

**Comment by parkerat2** [comment]
See you guys at 1 then

**Comment by naibinzheng** [comment]
Sorry guys, I'm out of town today, will be back at night. Anything I can
do, please tell me. Thanks

Naibin
