### ISSUE TITLE
needed functions

### ISSUE THREAD

**Issue by matts-dev** [ejcole/ChopStyx#6]
new_state = state.result(action)

actions_list = state.get_actions()

double_utility = state.utility(depth)

boolean = state.is_terminal()

**Comment by matts-dev** [comment]
maxer move = 0,

min move = 1

**Comment by matts-dev** [comment]
Hey guys, I'm basically done with my slides but I think we need some work on the others?

I finished the minimax algorithm but I didn't test it with our python state; I had a busy weekend with a wedding and family stuff. Unless someone else finishes cleaning up the python states (I think I saw some issue with utility function before I left friday) we might should just use the java output csvs. There probably was a bug, but it was at least beating a random agent more frequently that it was losing to the random agent.

**Comment by parkerat2** [comment]
I still have to do a few slides.  i have minimax working in python atm.
The internet was shit all day until about 2 hours ago.  So im wrapping
things up atm.  About to push the python rough changes
